// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xB-hYy2YEFlmYp2QgMk6-QhyZKwPRr4',
    appId: '1:406775095844:web:8ee670bb53801920982eb1',
    messagingSenderId: '406775095844',
    projectId: 'revdiet-962fe',
    authDomain: 'revdiet-962fe.firebaseapp.com',
    storageBucket: 'revdiet-962fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ryEmtpx0KzG8JVvekRwWNSriMaGui9U',
    appId: '1:406775095844:android:ea02e20589011ad8982eb1',
    messagingSenderId: '406775095844',
    projectId: 'revdiet-962fe',
    storageBucket: 'revdiet-962fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjqgkuzdZ2hV7EtE7VafiFomia53O2Qw',
    appId: '1:406775095844:ios:a5c59430a5ea584f982eb1',
    messagingSenderId: '406775095844',
    projectId: 'revdiet-962fe',
    storageBucket: 'revdiet-962fe.appspot.com',
    iosClientId: '406775095844-qesoh9a7mdnn8us0eiqlcsgqb804607d.apps.googleusercontent.com',
    iosBundleId: 'com.example.revdiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkjqgkuzdZ2hV7EtE7VafiFomia53O2Qw',
    appId: '1:406775095844:ios:a5c59430a5ea584f982eb1',
    messagingSenderId: '406775095844',
    projectId: 'revdiet-962fe',
    storageBucket: 'revdiet-962fe.appspot.com',
    iosClientId: '406775095844-qesoh9a7mdnn8us0eiqlcsgqb804607d.apps.googleusercontent.com',
    iosBundleId: 'com.example.revdiet',
  );
}
